### ISSUE TITLE
Add OARS

### ISSUE THREAD

**Issue by nedrichards** [flathub/io.github.FreeDM#4]
The appdata file that we use here doesn't have an OARS policy:

https://raw.githubusercontent.com/freedoom/freedoom/v0.11.3/dist/freedm.appdata.xml

This is now a flathub requirement and at some point the lack of it will prevent new builds being uploaded (not in the very short term, but at some point). Also, it'd be good to add! https://hughsie.github.io/oars/

**Comment by Alexander-Wilms** [comment]
Already reported upstream: https://github.com/freedoom/freedoom/issues/522
But since the last release was in 2017, patching it for Flathub might make sense.
